<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>io.github.eljah.busradio</groupId><artifactId>busradio-parent</artifactId><version>0.1.0</version></parent><artifactId>busradio-pi4j</artifactId><dependencies><dependency><groupId>io.github.eljah.busradio</groupId><artifactId>busradio-core</artifactId><version>${project.version}</version></dependency><dependency><groupId>com.pi4j</groupId><artifactId>pi4j-core</artifactId><version>${pi4j.version}</version></dependency><dependency><groupId>com.pi4j</groupId><artifactId>pi4j-plugin-gpiod</artifactId><version>${pi4j.version}</version></dependency><dependency><groupId>com.pi4j</groupId><artifactId>pi4j-plugin-raspberrypi</artifactId><version>${pi4j.version}</version></dependency></dependencies></project>
