'use strict';
let token='',state={},tracks=[];
const $=id=>document.getElementById(id);
const value=id=>$(id).value.trim();
const num=id=>Number(value(id));
const notify=text=>{$('notice').textContent=text;$('notice').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('notice').hidden=true,9000);};
async function request(path,method='GET',data){const headers={Authorization:'Bearer '+token};if(data!==undefined)headers['Content-Type']='application/json';const r=await fetch('/api/admin/'+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||r.status);return j;}
function form(id,fn){$(id).addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await fn();}catch(error){notify(error.message);}finally{b.disabled=false;}});}
function optionList(id,items,blank){const select=$(id),previous=select.value;select.replaceChildren();if(blank!==undefined)select.add(new Option(blank,''));items.forEach(([key,label])=>select.add(new Option(label,key)));if(items.some(x=>x[0]===previous))select.value=previous;}
function row(parent,title,detail){const div=document.createElement('div');div.className='row';const text=document.createElement('div');text.textContent=title;const small=document.createElement('small');small.textContent=detail;text.append(small);div.append(text);parent.append(div);return div;}
function renderTracks(){$('playlistTracks').replaceChildren();tracks.forEach((id,index)=>{const r=row($('playlistTracks'),`${index+1}. ${state.assets[id]?.name||id}`,id);const tools=document.createElement('div');tools.className='tools';[['↑',-1],['↓',1],['×',0]].forEach(([label,delta])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.className='subtle';b.onclick=()=>{if(delta===0)tracks.splice(index,1);else if(index+delta>=0&&index+delta<tracks.length)[tracks[index],tracks[index+delta]]=[tracks[index+delta],tracks[index]];renderTracks();};tools.append(b);});r.append(tools);});}
async function refresh(){state=await request('state');for(const [target,collection] of [['assetCount','assets'],['campaignCount','campaigns'],['deviceCount','devices']])$(target).textContent=Object.keys(state[collection]).length;$('revision').textContent=state.revision;
 const assets=Object.values(state.assets);optionList('trackSelect',assets.filter(a=>a.kind==='MUSIC').map(a=>[a.id,a.name]));optionList('adAsset',assets.filter(a=>a.kind==='AD').map(a=>[a.id,a.name]));const playlists=Object.values(state.playlists).map(p=>[p.id,p.name]);optionList('playlistSelect',playlists,'Новый');optionList('busPlaylist',playlists);optionList('campaignSelect',Object.values(state.campaigns).map(c=>[c.id,c.name]),'Новая');
 $('assets').replaceChildren();assets.forEach(a=>row($('assets'),a.name,`${a.kind} · ${(a.durationMs/1000).toFixed(1)} с · ${(a.bytes/1048576).toFixed(1)} MiB · ${a.id}`));
 $('campaigns').replaceChildren();Object.values(state.campaigns).forEach(c=>row($('campaigns'),c.name,`${c.id} · ${c.radiusMeters} м · ${c.maxPerDay}/день · ${c.routeId||'любой маршрут'}/${c.direction}`));
 $('routes').replaceChildren();Object.values(state.routes).forEach(r=>row($('routes'),`${r.number} · направление ${r.direction}`,`ID ${r.id} · ${r.points.length} точек · ${r.geometry}`));
 $('devices').replaceChildren();Object.values(state.devices).forEach(d=>row($('devices'),d.id,`Плейлист ${d.playlistId} · маршрут ${d.routeId}/${d.direction}`));renderTracks();
 const [events,beats]=await Promise.all([request('events'),request('heartbeats')]);$('events').replaceChildren();events.sort((a,b)=>b.time.localeCompare(a.time)).forEach(e=>{const tr=document.createElement('tr');[e.time,e.busId,e.status,e.campaignId||e.assetId,e.detail].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});$('events').append(tr);});$('heartbeats').replaceChildren();beats.forEach(h=>row($('heartbeats'),`${h.busId} · ${h.node.playback}`,`${h.receivedAt} · ревизия ${h.node.revision} · выход ${h.node.audioMode}`));
}
form('loginForm',async()=>{token=value('adminToken');await refresh();$('adminToken').value='';$('login').hidden=true;$('workspace').hidden=false;$('connection').textContent='Администратор · подключён';});
$('refresh').onclick=()=>refresh().catch(e=>notify(e.message));
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.hidden=t.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));});
form('uploadForm',async()=>{const f=$('audioFile').files[0];notify('Загрузка и подготовка аудио…');const r=await fetch('/api/admin/assets?kind='+value('assetKind')+'&name='+encodeURIComponent(f.name),{method:'POST',headers:{Authorization:'Bearer '+token},body:f});const j=await r.json();if(!r.ok)throw Error(j.error||r.status);await refresh();notify('Аудиофайл сохранён: '+j.id);});
$('addTrack').onclick=()=>{if(value('trackSelect'))tracks.push(value('trackSelect'));renderTracks();};
$('playlistSelect').onchange=()=>{const p=state.playlists[value('playlistSelect')];if(!p)return;for(const [id,key]of [['playlistId','id'],['playlistName','name'],['everyTracks','adEveryTracks'],['windowSeconds','adWindowSeconds'],['maxAds','maxAds']])$(id).value=p[key];tracks=[...p.tracks];renderTracks();};
form('playlistForm',async()=>{await request('playlist','PUT',{id:value('playlistId'),name:value('playlistName'),tracks,adEveryTracks:num('everyTracks'),adWindowSeconds:num('windowSeconds'),maxAds:num('maxAds')});await refresh();notify('Плейлист сохранён. Борта получат его при следующей разрешённой синхронизации.');});
const campaignFields={campaignId:'id',campaignName:'name',adAsset:'assetId',campaignRoute:'routeId',campaignDirection:'direction',adLat:'lat',adLon:'lon',radius:'radiusMeters',ahead:'aheadMeters',cooldown:'cooldownSeconds',dailyCap:'maxPerDay',priority:'priority',startsAt:'startsAt',endsAt:'endsAt'};
$('campaignSelect').onchange=()=>{const c=state.campaigns[value('campaignSelect')];if(!c)return;Object.entries(campaignFields).forEach(([id,key])=>$(id).value=c[key]);$('aheadOnly').checked=c.aheadOnly;};
$('startsAt').value=new Date().toISOString();$('endsAt').value=new Date(Date.now()+30*86400000).toISOString();
form('campaignForm',async()=>{const c={};Object.entries(campaignFields).forEach(([id,key])=>c[key]=['direction','lat','lon','radiusMeters','aheadMeters','cooldownSeconds','maxPerDay','priority'].includes(key)?num(id):value(id));c.aheadOnly=$('aheadOnly').checked;c.startsAt=new Date(c.startsAt).toISOString();c.endsAt=new Date(c.endsAt).toISOString();await request('campaign','PUT',c);await refresh();notify('Кампания сохранена. Для остановки задайте прошедшее время окончания и синхронизируйте борта.');});
form('routeImportForm',async()=>{const data=JSON.parse(await $('routeFile').files[0].text());const result=await request('import-buscrawl','POST',data);await refresh();notify('Импортировано направлений: '+result.importedDirections);});
form('routeForm',async()=>{await request('route','PUT',JSON.parse(value('routeJson')));await refresh();notify('Геометрия сохранена.');});
form('deviceForm',async()=>{const result=await request('device','POST',{id:value('busId'),playlistId:value('busPlaylist'),routeId:value('busRoute'),direction:num('busDirection')});$('deviceToken').textContent=`Борт: ${result.id}\nBUSRADIO_NODE_TOKEN=${result.token}\nСохраните ключ. Не публикуйте его в Git.`;$('deviceToken').hidden=false;await refresh();notify('Регистрация сохранена.');});

$('reassign').onclick=async()=>{try{await request('assignment','PUT',{id:value('busId'),playlistId:value('busPlaylist'),routeId:value('busRoute'),direction:num('busDirection')});await refresh();notify('Назначение изменено, ключ сохранён.');}catch(e){notify(e.message);}};
