package io.github.eljah.busradio.core;
import java.time.*;
import java.util.*;
import static io.github.eljah.busradio.core.Json.*;

public final class Model {
 private Model(){}
 public static final int SAMPLE_RATE=22050, BYTES_PER_SECOND=SAMPLE_RATE*2;
 public record Point(double lat,double lon){public Point{if(!Double.isFinite(lat)||!Double.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)throw new IllegalArgumentException("Invalid WGS84 position");}public static Point from(Object x){var m=obj(x);return new Point(num(m,"lat"),num(m,"lon"));}}
 public record Fix(Point point,double speedMps,double course,double accuracyM,Instant at,String source){public Fix{Objects.requireNonNull(point);Objects.requireNonNull(at);if(!Double.isFinite(speedMps)||speedMps<0||speedMps>100||!Double.isFinite(course)||course<0||course>=360||!Double.isFinite(accuracyM)||accuracyM<0)throw new IllegalArgumentException("Invalid fix");}public boolean fresh(Instant now){long age=Duration.between(at,now).toMillis();return age>=-2000&&age<=15000&&accuracyM<=75;}public static Fix from(Object x){var m=obj(x);return new Fix(Point.from(m.get("point")),num(m,"speedMps"),num(m,"course"),num(m,"accuracyM"),Instant.parse(str(m,"at")),str(m,"source"));}}
 public record Asset(String id,String name,String sha256,long bytes,String kind,String rights){public Asset{FilesEx.id(id);FilesEx.hash(sha256);if(bytes<=0||bytes%2!=0||bytes>BYTES_PER_SECOND*3600L)throw new IllegalArgumentException("Invalid PCM length");if(!Set.of("MUSIC","AD","FILLER").contains(kind)||name==null||name.isBlank()||rights==null||rights.isBlank())throw new IllegalArgumentException("Name, kind and rights required");}public long frames(){return bytes/2;}public static Asset from(Object x){var m=obj(x);return new Asset(str(m,"id"),str(m,"name"),str(m,"sha256"),lng(m,"bytes"),str(m,"kind"),str(m,"rights"));}}
 public record Route(String id,String name,String direction,String geometry,List<Point> points){public Route{FilesEx.id(id);Objects.requireNonNull(name);Objects.requireNonNull(direction);if(!Set.of("STOP_CHORDS","SHAPE").contains(geometry))throw new IllegalArgumentException("geometry must be STOP_CHORDS or SHAPE");points=List.copyOf(points);if(points.size()<2||points.size()>20000)throw new IllegalArgumentException("Route needs 2..20000 points");}public static Route from(Object x){var m=obj(x);return new Route(str(m,"id"),str(m,"name"),str(m,"direction"),str(m,"geometry"),arr(m.get("points")).stream().map(Point::from).toList());}}
 public record Slot(String type,String assetId,int seconds,int maxAds,String fallbackAssetId){public Slot{if(!Set.of("MUSIC","AD_WINDOW").contains(type))throw new IllegalArgumentException("Invalid slot type");if(type.equals("MUSIC"))FilesEx.id(assetId);else if(seconds<1||seconds>600||maxAds<1||maxAds>10)throw new IllegalArgumentException("Invalid advertisement window");if(fallbackAssetId!=null&&!fallbackAssetId.isBlank())FilesEx.id(fallbackAssetId);}public static Slot from(Object x){var m=obj(x);return new Slot(str(m,"type"),str(m,"assetId",""),(int)num(m,"seconds",60),(int)num(m,"maxAds",2),str(m,"fallbackAssetId",""));}}
 public record Playlist(String id,String name,List<Slot> slots){public Playlist{FilesEx.id(id);slots=List.copyOf(slots);if(slots.isEmpty()||slots.size()>1000)throw new IllegalArgumentException("Playlist needs 1..1000 slots");}public static Playlist from(Object x){var m=obj(x);return new Playlist(str(m,"id"),str(m,"name"),arr(m.get("slots")).stream().map(Slot::from).toList());}}
 public record Campaign(String id,String name,String assetId,List<String> routeIds,Point point,double radiusM,double maxAheadM,int horizonSeconds,int priority,int cooldownSeconds,int maxPerDay,Instant startsAt,Instant endsAt,String zone,String dailyStart,String dailyEnd,boolean enabled){
  public Campaign{FilesEx.id(id);FilesEx.id(assetId);routeIds=List.copyOf(routeIds);if(routeIds.isEmpty())throw new IllegalArgumentException("Explicit route directions required");routeIds.forEach(FilesEx::id);Objects.requireNonNull(point);if(!Double.isFinite(radiusM)||radiusM<10||radiusM>10000||!Double.isFinite(maxAheadM)||maxAheadM<10||maxAheadM>10000||horizonSeconds<1||horizonSeconds>1800||cooldownSeconds<0||maxPerDay<1||maxPerDay>10000||priority<0||priority>1000)throw new IllegalArgumentException("Invalid campaign limits");if(!endsAt.isAfter(startsAt))throw new IllegalArgumentException("Invalid campaign dates");ZoneId.of(zone);LocalTime.parse(dailyStart);LocalTime.parse(dailyEnd);}
  public static Campaign from(Object x){var m=obj(x);return new Campaign(str(m,"id"),str(m,"name"),str(m,"assetId"),arr(m.get("routeIds")).stream().map(Object::toString).toList(),Point.from(m.get("point")),num(m,"radiusM"),num(m,"maxAheadM"),(int)num(m,"horizonSeconds"),(int)num(m,"priority"),(int)num(m,"cooldownSeconds"),(int)num(m,"maxPerDay"),Instant.parse(str(m,"startsAt")),Instant.parse(str(m,"endsAt")),str(m,"zone"),str(m,"dailyStart"),str(m,"dailyEnd"),bool(m,"enabled",true));}
 }
 public record Manifest(int schema,String busId,String revision,Instant publishedAt,Playlist playlist,Route route,List<Route> alternatives,List<Asset> assets,List<Campaign> campaigns){
  public Manifest{if(schema!=1)throw new IllegalArgumentException("Unsupported manifest schema");FilesEx.id(busId);FilesEx.id(revision);alternatives=List.copyOf(alternatives);assets=List.copyOf(assets);campaigns=List.copyOf(campaigns);List<Route> all=new ArrayList<>();all.add(route);all.addAll(alternatives);validate(playlist,all,assets,campaigns);}
  public List<Route> allRoutes(){List<Route> all=new ArrayList<>();all.add(route);all.addAll(alternatives);return List.copyOf(all);}
  public Manifest onRoute(Route selected){return new Manifest(schema,busId,revision,publishedAt,playlist,selected,allRoutes().stream().filter(r->!r.id().equals(selected.id())).toList(),assets,campaigns);}
  public Map<String,Asset> assetMap(){Map<String,Asset> m=new LinkedHashMap<>();assets.forEach(a->m.put(a.id(),a));return m;}
  public static Manifest from(Object x){var m=obj(x);return new Manifest((int)lng(m,"schema"),str(m,"busId"),str(m,"revision"),Instant.parse(str(m,"publishedAt")),Playlist.from(m.get("playlist")),Route.from(m.get("route")),arr(m.getOrDefault("alternatives",List.of())).stream().map(Route::from).toList(),arr(m.get("assets")).stream().map(Asset::from).toList(),arr(m.get("campaigns")).stream().map(Campaign::from).toList());}
 }
 public static void validate(Playlist p,List<Route> routes,List<Asset> assets,List<Campaign> ads){
  Set<String> routeIds=new HashSet<>();for(Route r:routes)if(!routeIds.add(r.id()))throw new IllegalArgumentException("Duplicate route direction");
  Set<String> ids=new HashSet<>();for(var a:assets)if(!ids.add(a.id()))throw new IllegalArgumentException("Duplicate asset");
  for(var s:p.slots()){if(s.type().equals("MUSIC")&&!ids.contains(s.assetId()))throw new IllegalArgumentException("Missing music asset "+s.assetId());if(s.fallbackAssetId()!=null&&!s.fallbackAssetId().isBlank()&&!ids.contains(s.fallbackAssetId()))throw new IllegalArgumentException("Missing fallback");}
  Set<String> campaigns=new HashSet<>();for(var a:ads){if(!campaigns.add(a.id())||!ids.contains(a.assetId())||a.routeIds().stream().noneMatch(routeIds::contains))throw new IllegalArgumentException("Invalid campaign in release");Asset asset=assets.stream().filter(z->z.id().equals(a.assetId())).findFirst().orElseThrow();if(!asset.kind().equals("AD"))throw new IllegalArgumentException("Campaign must use an AD asset");}
 }
 public static boolean inWindow(LocalTime now,LocalTime start,LocalTime end){if(start.equals(end))return true;return start.isBefore(end)?!now.isBefore(start)&&now.isBefore(end):!now.isBefore(start)||now.isBefore(end);}
}
