package io.github.eljah.busradio.server;
import io.github.eljah.busradio.core.FilesEx;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.CountDownLatch;
public final class ServerMain {
 public static void main(String[] args)throws Exception{
  var env=System.getenv();Store store=new Store(Path.of(env.getOrDefault("BR_DATA","var/server")));boolean demo=Arrays.asList(args).contains("--demo");String token=demo?DemoData.install(store):null;
  String password=env.get("BR_ADMIN_PASSWORD");if(password==null){password=FilesEx.token();System.out.println("One-time generated admin password: "+password);}
  String bind=env.getOrDefault("BR_BIND","127.0.0.1");int port=Integer.parseInt(env.getOrDefault("BR_PORT","8080"));
  RadioServer server=new RadioServer(store,bind,port,password,env.get("BR_PUBLIC_ORIGIN"),env.getOrDefault("BR_FFMPEG","ffmpeg"));
  if(token!=null){Path p=store.root.resolve("demo-edge.properties");String config="server=http://127.0.0.1:"+server.port()+"\nbus.id=demo-bus\nbus.token="+token+"\nserver.publicKey="+store.publicKey+"\ncache.dir=var/demo-edge\nsync.demoLoopback=true\naudio.mode=wav\naudio.file=var/demo-aircheck.wav\ngps.mode=demo\nhardware.enabled=false\nrf.enabled=false\n";FilesEx.atomic(p,config.getBytes(StandardCharsets.UTF_8));Store.privateFile(p);System.out.println("Synthetic demo enrollment: "+p);}
  Runtime.getRuntime().addShutdownHook(new Thread(()->{server.close();try{store.close();}catch(Exception ignored){}}));server.start();System.out.println("busradio admin: http://"+bind+":"+server.port()+" (RF is never generated by the server)");new CountDownLatch(1).await();
 }
}
